### Site Settings ###
title: erickqian
description: >- 
  Just do it.
baseurl: ""
url: ""
repository: erickqian/erickqian.github.io

### categories、tags path ###
archive_dir: pages/archive
tag_dir: pages/tags
category_dir: pages/categories

# Build settings
markdown: kramdown

### Plugins ###
plugins:
  - jekyll-feed

### Navbar Settings ###
# The following paths are excluded from navbar
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/categories.html

### Author Info ###
author:
  name              : erickqian
  image             : https://s2.loli.net/2022/03/22/JyQx6VB8vIiZsr2.jpg
  email             : qianyunkang@gmail.com
  github            : erickqian
# twitter           : your_username
# linkedin          : your_username
# facebook          : your_username
# dribbble          : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Comments ###
comments:
  provider: gitalk # "disqus", "gitalk", "valine"
  ### Disqus ###
  disqus:
    shortname: https-YogKnight-GitHub-io # the Disqus shortname for the site

  ### Gitalk ###
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : 1e87a852118b89bf0689 # GitHub Application Client ID
    clientSecret: ffd6d23fb05c906bc5ace64db6fc403bb8d38316 # GitHub Application Client Secret
    repository  : erickqian.github.io # GitHub repo
    owner       : erickqian # GitHub repo owner
    admin: erickqian # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.

  ### Valine ###
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : nvKhhaSS9ecf2X8yEeMgeJhG-gzGzoHsz # LeanCloud App id
    app_key     : xGBXXtpdHAJBmigEUOLCmhBV # LeanCloud App key
    placeholder : 评论 # Prompt information

### page view ###
pageview:
  provider: leancloud
  leancloud:
    app_id    : DeAb9qzrQbDK3VApHPKCAbk1-9Nh9j0Va
    app_key   : RWtJMvC3zFhNeDGCUcXrCXLw
    app_class : Blog_Views

#### Analytics ###
analytics:
  # google
  provider: google 

  # Google Analytics
  google:
    # Google Analytics id for the site
    tracking_id : UA-122466435-1


### Sharing ###
sharing:
  provider: addtoany # "addtoany"

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

### Posts default Permalink ###
permalink: blog/:title

### About Footer ###
sitelink: https://erickqian.github.io/
repositoryurl: https://github.com/erickqian/erickqian.github.io
zipurl: https://github.com/erickqian/erickqian.github.io/archive/refs/heads/master.zip


### Exclude from processing. ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock